/** Seed data: 0–48 Hours Planning After Fasal — Indore Ashara 1448H */
const PLANNING_META = {
  title: "0–48 Hour on Fasal",
  location: "Indore Ashara 1448H",
  sheetTitle: "0 - 48 HOURS PLANNING AFTER FASAL",
};

const COLUMNS = [
  { key: "sno", label: "S.No.", width: 56 },
  { key: "task", label: "TASK", width: 320 },
  { key: "assignedTo", label: "ASSIGNED TO", width: 220 },
  { key: "dependency", label: "DEPENDENCY", width: 140 },
  { key: "priority", label: "Priority", width: 100 },
  { key: "zone", label: "ZONE", width: 120 },
  { key: "remarks", label: "Remarks (if any)", width: 200 },
];

const EMPTY_ROW = () => ({
  sno: "",
  task: "",
  assignedTo: "",
  dependency: "",
  priority: "",
  zone: "",
  remarks: "",
});

function padRows(rows, count = 10) {
  const out = rows.map((r, i) => ({ ...EMPTY_ROW(), ...r, sno: r.sno ?? i + 1 }));
  while (out.length < count) {
    out.push({ ...EMPTY_ROW(), sno: out.length + 1 });
  }
  return out;
}

const DEPARTMENTS = [
  {
    id: "mawaid",
    name: "MAWAID",
    chairman: "HATIM BHAI BARNAGARWALA",
    pc: "JUZER BHAI MALUQAMRUDDIN",
    rows: padRows([
      { task: "TAYYEBI MAWAID 100 THAAL JAMAN FOR HR", assignedTo: "MURTUZA MUNAQIBWALA", dependency: "FMB/COD", priority: "Critical", zone: "ALL ZONES" },
      { task: "UTENSIL PROCURMENT-SPPLY CHAIN-STORAGE", assignedTo: "ABDUL QADIR BHAI", dependency: "CHAIRMEN", zone: "CMZ" },
      { task: "ZABIHAT INCHARGE APPOINTMENT", assignedTo: "SHABBIR BHAI MHOWWALA", dependency: "CHAIRMEN", zone: "CMZ" },
      { task: "MSB MAWAID EXECUTION FOR 40 THAALS", assignedTo: "HATIM BHAI BADNAGAR WAL", dependency: "COD", priority: "Critical", zone: "CMZ" },
      { task: "PO ORDER GENERATION & ORDER PLACEMENT OF FOOD", assignedTo: "TALIB BHAI GHEEWALA", dependency: "COD", priority: "Critical", zone: "CMZ" },
      { task: "CREATION OF EXTENDED KITCHEN", assignedTo: "JUZER BHAI KHOKAWALA", dependency: "MAWAID", priority: "High", zone: "ALL ZONES" },
      { task: "FOOD PACKETS PREPARATION FOR IBADULLAH HR", assignedTo: "JUZER BHAI DEWASWALA", dependency: "FMB(PREPRATION)/WB(DISTRIBUTION", priority: "High", zone: "CMZ" },
      { task: "PROCURMENT OF DISPOSABLES, INGREIDIENTS, SIGNAGES", assignedTo: "HUSAIN BHAI KHAMBATI", dependency: "PROCURMENT", priority: "High", zone: "CMZ" },
      { task: "FOOD TRIAL & TASTE CHECK", assignedTo: "JUZER BHAI KHOKAWALA", dependency: "CHAIRMEN", priority: "High", zone: "CMZ" },
      { task: "DANA COMMITTEE FORMATION", assignedTo: "TAHER BHAI RAJGARHWALA", dependency: "MAWAID", priority: "Medium", zone: "CMZ" },
      { task: "MAARAZ PREPARATION", assignedTo: "BATUL BEN CHAKKI WALA", dependency: "MAWAID", priority: "Medium", zone: "CMZ" },
      { task: "AUDIT FOR COOKS", assignedTo: "M. SADIQUE BHAI SPIRIT WAL", dependency: "MAWAID", zone: "CMZ" },
    ], 12),
  },
  {
    id: "sabeel",
    name: "SABEEL",
    chairman: "HATIM BHAI BARNAGARWALA",
    pc: "JUZER BHAI MALUQAMRUDDIN",
    rows: padRows([
      { task: "CHAI FOR ALL HR (CMZ)", assignedTo: "MUFADDAL AMJHERAWALA", priority: "Critical", zone: "CMZ" },
      { task: "PROCUREMENT OF UTENSILS", assignedTo: "AUN CHAKKIWALA", dependency: "PROCURMENT", priority: "High", zone: "CMZ" },
      { task: "PROCUREMENT OF (INGRIDIENTS, DISPOSABLES ETC)", assignedTo: "TAHA SEVA", dependency: "PROCURMENT", priority: "High", zone: "CMZ" },
    ]),
  },
  {
    id: "hygiene",
    name: "HYGIENE",
    chairman: "Dr. FAZAL HUSAIN BHAI",
    pc: "JUZER BHAI MALUQAMRUDDIN",
    rows: padRows([
      { task: "VENDOR AND RAW MATERIAL CHECKS", assignedTo: "Ali Rangwala", priority: "High", zone: "CMZ" },
      { task: "WATER SAFETY (COOKING AND DRINKING)", assignedTo: "Dr. Fazal Husain", priority: "Critical", zone: "CMZ" },
      { task: "PROCUREMENT (EQUIPMENTS)", assignedTo: "Dr. fazal Husain", dependency: "PROCURMENT", priority: "High", zone: "CMZ" },
    ]),
  },
  {
    id: "karamat",
    name: "KARAMAT",
    chairman: "M. YUSUF BHAI SHAJAPURWALA",
    pc: "HATIM BHAI KANCHWALA",
    rows: padRows([
      { task: "DISTRIBUTION OF FOOD PACKETS FOR IBADULLAH", assignedTo: "Shabbir Bhai Hatodwala", dependency: "MAWAID", priority: "Critical", zone: "CMZ" },
      { task: "DISTRIBUTION OF WATER BOTTLES", assignedTo: "Abbas Bhai Arsiwala", priority: "Critical", zone: "CMZ" },
      { task: "HYDERATION POINT SETUP", assignedTo: "Mustafa Bhai Haveli wala", dependency: "BGI & Sabeel", priority: "Medium", zone: "CMZ" },
      { task: "Start the Procurement process and liason with Procurement department", assignedTo: "Hussain bhai Tinwala", dependency: "PROCUREMENT", priority: "Critical", zone: "All Zones" },
      { task: "COUNT FOR FOOD PACKETS REQUIRED", assignedTo: "Hussain Bhai Tinwala", dependency: "HR", priority: "Critical" },
      { task: "Confirm all Karamat teams are present and deployed.", assignedTo: "Mustafa Bhai Haveli wala" },
      { task: "Liason with IPMO Heads and prepare an admin office", assignedTo: "Mustafa Bhai Haveli wala" },
      { task: "Monitor Central and zonal Procurement Office creation in liasoning with Construction", assignedTo: "Huzefa Bhai Amjherawala" },
    ]),
  },
  {
    id: "mmr",
    name: "MMR",
    chairman: "HUSAIN BADWANIWALA",
    pc: "MUSTANSIR BH DAWAIWALA",
    rows: padRows([
      { task: "SPACE ALLOCATION ON AIRPORT & RAILWAYS", dependency: "PR", priority: "Critical" },
      { task: "WELCOME KIT PO ORDER", assignedTo: "Husain bhai badwaniwala", dependency: "PROCURMENT", priority: "HIGH" },
      { task: "BUILD MMR CENTRES IN ALL ZONES", assignedTo: "HUSAIN bhai badwaniwala", priority: "HIGH" },
    ]),
  },
  {
    id: "construction",
    name: "CONSTRUCTION",
    chairman: "SHK SAIFUDDIN KHAMBATI",
    pc: "HUZAIFA BHAI ARIF",
    rows: padRows([
      { task: "Ground levelling work for dome installation", priority: "Critical", zone: "CMZ" },
      { task: "Ground levelling work for dome installation", assignedTo: "Husain bhai Saify", priority: "High", zone: "MASAKIN" },
      { task: "Ground levelling work for dome installation", assignedTo: "Husain bhai Saify", priority: "High", zone: "BURHANI" },
      { task: "Ground levelling work for dome installation", zone: "HASANJI" },
      { task: "Ground levelling work for dome installation", assignedTo: "Hatim bhai Sanawadwala", priority: "High", zone: "NOORANINAGAR" },
      { task: "Ground levelling work for dome installation", zone: "MHOW" },
      { task: "Ground levelling work for dome installation", assignedTo: "Husain bhai Engineeringwala", priority: "High", zone: "HAIDRY" },
      { task: "DG set procurement", assignedTo: "Juzer bhai Badshah", dependency: "PROCURMENT", priority: "High", zone: "CMZ" },
      { task: "VENDOR FINALIZATION", assignedTo: "Shk Saifuddin Khambati", priority: "High", zone: "ALL ZONES" },
      { task: "LABOUR RECRUITMENT", dependency: "HR", priority: "High", zone: "CMZ" },
      { task: "ELECTRICITY APPROVAL", assignedTo: "Aziz bhai Bootwala", dependency: "PR", priority: "Critical", zone: "ALL ZONES" },
      { task: "HVAC LOGISTICS", assignedTo: "Khuzaima bhai Ujjainwala", priority: "High", zone: "ALL ZONES" },
    ], 12),
  },
  {
    id: "medical",
    name: "MEDICAL",
    chairman: "DR TAHA BH SETHJIWALA",
    pc: "KAUSER BHAI SHAKIR",
    rows: padRows([
      { task: "Appoint a liaison to cooridnate with the PMO", priority: "Critical" },
      { task: "Appoint a person from umoor Sehat for Ashara Mubaraka, including hospital based doctors", priority: "High" },
      { task: "Prepare and Implment an operational plan realted to umoor us Sehat", priority: "High" },
      { task: "Manage doctors HR matters and ensure increased and comprehensive doctor's coverage", priority: "High" },
      { task: "Ensure procurement of all essentials medical equipments and supplies", priority: "High" },
      { task: "Ensure all instructions issued by PMO is implemented accordingly", priority: "High" },
      { task: "Under this system, passes for doctors are issued through Umoor Sehat as per approved quota", priority: "High" },
      { task: "Appoint health related liasions with other departments", priority: "High" },
      { task: "Maintsin sn updated record of medical requirements, ensure availaibility", priority: "Medium" },
      { sno: 10, priority: "High" },
    ]),
  },
  {
    id: "tazyeen",
    name: "TAZYEEN",
    chairman: "ABDULQADIR BHAI MHOWWALA",
    pc: "HATIM BHAI KANCHWALA",
    rows: padRows([
      { task: "Create workshop for Tazyeen at Khambati Plot near Masjid", assignedTo: "Abdulqadir bhai Mhowwal", dependency: "CONSTRUCTION", priority: "High", zone: "CMZ" },
      { task: "Clear Qibla Area of CMZ and prepare site readiness for the same - install metal scaffolding at Qibla 11ft x 34 ft", assignedTo: "Shoab Barnagarwala", dependency: "CONSTRUCTION", priority: "High", zone: "CMZ" },
      { task: "Intall Alam at CMZ Area", assignedTo: "Aliakbar Sabir", dependency: "PR", priority: "Med", zone: "CMZ" },
    ]),
  },
  {
    id: "cmd",
    name: "CMD",
    chairman: "HUSAIN BHAI RATLAMWALA",
    pc: "HUZAIFA BHAI ARIF",
    rows: padRows([
      { task: "WINDUP AND STORAGE OF ALL EXISTING MATERIAL OF MASJID", assignedTo: "Taher bhai Ratlamwala", priority: "Critical", zone: "CMZ" },
      { task: "MATAMI MAJLIS", assignedTo: "MULA AMMAR BHAI JAWRAWALA", priority: "Critical", zone: "CMZ" },
      { task: "ZABIYAT (SADAQA SANGHI +MASJID", assignedTo: "MUSTUFA BHAI TEHSILDAR", priority: "Critical", zone: "CMZ" },
      { task: "DISPERSAL OF PUBLIC", assignedTo: "MULLA MURTAZA MITHAIWALA", priority: "Critical", zone: "CMZ" },
      { task: "MASJID MATERIAL REMOVAL", assignedTo: "YUNUS BHAI SALIM", priority: "Critical", zone: "CMZ" },
      { task: "SEHAN MATERIAL REMOVAL", assignedTo: "MULLA MOIZ BH ASHTAWALA", priority: "Critical", zone: "CMZ" },
      { task: "MOHAMMEDI JAMAT KHANA REMOVAL", assignedTo: "HUZEFA BHAI AMJERAWALA", priority: "Medium", zone: "CMZ" },
      { task: "ELECTRIC JHUMAR ,FANS", assignedTo: "ASGER BHAI ELECTRICIAN", priority: "High", zone: "CMZ" },
      { task: "SOUND SYSTEM", assignedTo: "KHUZEMA BHAI NADEEM", priority: "High", zone: "CMZ" },
      { task: "VIDEO (TV, SCREEN ,PROJECTOR", assignedTo: "MULLA MUSTUFA BHAI BADSHAH", priority: "High", zone: "CMZ" },
      { task: "CARPET", assignedTo: "BGI+ SHABAB+HSB+TOLABA", priority: "High", zone: "CMZ" },
      { task: "UMOOR OFFICES GF", assignedTo: "YUNUS BHAI SALIM", priority: "Medium", zone: "CMZ" },
      { task: "AIR CONDITIONERS", assignedTo: "KHUZEMA BHAI UJJAINWALA", priority: "Medium", zone: "CMZ" },
      { task: "PLANTATIONS", assignedTo: "MULLA TURAB BHAI KANCHWALA", priority: "Medium", zone: "CMZ" },
      { task: "MASJID WINDOW DOORS", assignedTo: "SHAIKH SAIFUDDIN BHAI KHAMBATI", priority: "High", zone: "CMZ" },
    ], 15),
  },
  {
    id: "fire-safety",
    name: "FIRE & SAFETY",
    chairman: "HUSAIN BHAI BANDOOKWALA",
    pc: "MUSTANSIR BH DAWAIWALA",
    rows: padRows([
      { task: "FIRE & SAFETY CHECK ON ALL CONSTRUCTION SITES", assignedTo: "HUSAIN BH BANDOOKWALA", dependency: "CONSTRUCTION", priority: "Critical", zone: "ALL ZONES" },
      { task: "DEFINE COMMAND STRUCTURE AND FIRE COMMAND CENTRE", assignedTo: "HUSAIN BH BANDOOKWALA", dependency: "CONSTRUCTION", priority: "High", zone: "ALL ZONES" },
      { task: "INSTALLATION OF FIRE EXTINGUSHERS ON CONSTRUCTION SITE", assignedTo: "HUSAIN BH BANDOOKWALA", dependency: "CONSTRUCTION", priority: "High", zone: "ALL ZONES" },
      { task: "PERMISSION PROCESS FOR FIRE EXTINGUSHER VANS", assignedTo: "MUSTAFA BH SHAH", dependency: "PR", priority: "High", zone: "ALL ZONES" },
      { task: "EXECUTE SAFETY DRILLS IN EVERY CLUSTER", assignedTo: "HUZEFA BH PATANWALA", priority: "High", zone: "ALL ZONES" },
      { task: "CO ORDINATE WITH FLOW FOR ACTUAL LAYOUT", assignedTo: "HUSAIN BH BANDOOKWALA", dependency: "FLOW", priority: "High", zone: "ALL ZONES" },
      { task: "PROCURE FIRE FIGHTING EQUIPMENTS", assignedTo: "YUSUF BH AMJHERAWALA", dependency: "PROCUREMENT", priority: "Critical", zone: "ALL ZONES" },
      { task: "PERMISSION  FOR FIRE TRUCKS AND OTHER STANDBY REQUIREMENTS", assignedTo: "MUSTAFA BH AMJHERAWALA", dependency: "PR", priority: "Critical", zone: "ALL ZONES" },
    ]),
  },
  {
    id: "transport",
    name: "TRANSPORT",
    chairman: "HUSAIN BHAI RANGWALA",
    pc: "KAUSER BHAI SHAKIR",
    rows: padRows([
      { task: "BUS COUNT FINALIZATION", assignedTo: "Juzer Bhai Babukhanwala", priority: "High", zone: "ALL ZONES" },
      { task: "VENDOR FINALIZATION", assignedTo: "Juzer Bhai Babukhanwala", priority: "Medium", zone: "ALL ZONES" },
    ]),
  },
  {
    id: "flow",
    name: "FLOW MANAGEMENT",
    chairman: "HUZAIFA BHAI SURGICALWALA",
    pc: "KAUSER BHAI SHAKIR",
    rows: padRows([
      { task: "BG INTERNATIONAL OFFICE SETUP WITH FAST INTERNET ACCESS AND ALL EQUIPMENTS AS PER PROCUREMENT", assignedTo: "Husain Bhai Betmawala", dependency: "CONSTRUCTION", priority: "Critical", zone: "CMZ" },
      { task: "SECURING QASR MUBARAK AND MASJID SURROUNDINGS", priority: "Critical", zone: "CMZ" },
      { task: "MAKE MASJID SURROUNDINGS A NO VEHICLE ZONE AND ALLOW ONLY PASS HOLDERS VEHICLES", priority: "Critical", zone: "CMZ" },
      { task: "ALLOW MOVEMENT OF PAID WORKERS, DOMESTIC WORKERS,CONSTRUCTION STAFF AND AUTHORITIES WITH ID CARDS" },
      { task: "ISSUES ID CARDS TO ALL WORKERS AND VOLUNTEERS WITH MASJID PREMISES ACCESS" },
      { task: "ACTIVATE COMMAND CENTRAL WITH CCTV, WALKIE NETWORK AND ESCALATION DESK" },
      { task: "DEPLOY BARRICADES, SCANNERS, SIGNAGES, EMERGENCY ACCESS ROUTES AND QUEUE CHANNELING SYSTEMS" },
      { task: "COORDINATE WITH TRANSPORT FOR SEAMLESS DROP OFF TO ENTRY GATE MOVEMENT" },
      { task: "CONDUCT ROUTE TESTING, EMERGENCY EVACUATION DRILLS AND SCANNER SIMULATIONS" },
      { task: "ENSURE DEDICATED ARRANGENENTS FOR SENIOR CITIZENS, MOTHERS WITH CHILDREN AND SPECIAL NEED MUMINEEN" },
    ]),
  },
  {
    id: "security",
    name: "SECURITY",
    chairman: "ABDULQADIR BHAI MUKHIYA",
    pc: "KAUSER BHAI SHAKIR",
    rows: padRows([
      { task: "ACTIVATE SECURITY COMMAND AND CONTROL OPERATIONS", assignedTo: "Kauser alli Tinwala", dependency: "HR", priority: "Critical", zone: "CMZ" },
      { task: "DEPLOY SECURITY PERSONNEL ACROSS ALL SENSITIVE ZONES", assignedTo: "Abbas Amjherawla", dependency: "IT", priority: "High", zone: "CMZ" },
      { task: "ESTABLISH SECURITY CHECKPOINTS WITH MANDATORY VERIFICATION PROCEDURE AT ALL SENSITIVE ACCESS LOCATIONS", priority: "High", zone: "CAT ROAD" },
      { task: "ISSUE, REGISTER AND CONTINUOUSLY VERIFY ID CARS/PASSES FOR RESIDENTS, MAIDS, CONSTRUCTION LABOURS, PAID WORKERS, KGs AND AUTHORIZED PERSONNEL" },
      { task: "SECURE RESTRICTED AREAS AND CONSTRUCTION AREAS" },
      { task: "ACTIVATE SURVEILLANCE AND MONITORING SYSTEMS" },
      { task: "CONDUCT SECURITY STAFF BREIFING AND OPERATIONAL READINESS" },
    ]),
  },
  {
    id: "nazafat",
    name: "NAZAFAT",
    chairman: "MUSTAFA BHAI PATANWALA",
    pc: "KAUSER BHAI SHAKIR",
    rows: padRows([
      { task: "IMMEDIATE HOD MEETING IN RESPECTIVE ZONES", priority: "Critical", zone: "ALL ZONES" },
      { task: "TAKEOVER THE IMMEDIATE NAZAFAT TASKS FOR RESPECTIVE MASJID/MARKAZ AND MAWAID", priority: "Critical", zone: "CMZ" },
      { task: "CONNECT WITH PROCUREMENT TEAM FOR IMMEDIATE DEPLOY OF ALL NAZAFAT MATERIAL", priority: "High", zone: "CMZ" },
      { task: "IDENTIFY ALL THE OPERATIONAL WASTE GENERATION POINTS( E.G SABEEL STALLS, TEA/COCONUT HUBS, HAWKERS, MEDICAL ZONES)" },
      { task: "COORDINATE WITH THE CENTRAL PR TEAM TO ALIGN PARAMETERS WITH LOCAL MUNICIPAL WASTE NETWORK AND NEARBY NEIGHBORHOOD ASSOCIATIONS" },
    ]),
  },
  {
    id: "finance",
    name: "FINANCE",
    chairman: "SHK TAHER BHAI SETHJIWALA",
    pc: "AHMED BHAI",
    rows: padRows([
      { task: "Collection of Funds from Each Zone, based on pre decided share of respective zones", assignedTo: "M Moiz Hakimi", priority: "Critical", zone: "ALL ZONES" },
      { task: "Release allocated funds to departments as per the approved budget for immediate requirements.", assignedTo: "M Moiz Hakimi", priority: "Critical", zone: "ALL ZONES" },
      { task: "Release of Software for Accounitng entries and record keeping", assignedTo: "Murtuza Bhaktawari", priority: "High", zone: "ALL ZONES" },
      { task: "Training of Member of software", assignedTo: "Murtuza Bhaktawari", priority: "High", zone: "ALL ZONES" },
    ]),
  },
  {
    id: "pr",
    name: "PR",
    chairman: "SHK KHUZAIMA BHAI PETIWALA",
    pc: "HUZAIFA BHAI ARIF",
    rows: padRows([
      { task: "LETTER & INVITATION TO ALL GOVERNMENT AUTHORITIES", assignedTo: "Murtaza Bhai Panbihar Wala / Muffaddal Bhai", priority: "Critical", zone: "ALL ZONES" },
      { task: "GET APPROVAL FOR ALL PR REQUISITIONS IN GOVERNMEN DEPT.", assignedTo: "Zulfiqar Bhai Rang Wala / Muffaddal Bhai Baroda", priority: "Critical", zone: "ALL ZONES" },
      { task: "LETTER IN MPEB AUTHORITIES", assignedTo: "Mustafa Bhai Maluqamruddin Wala /", priority: "Critical", zone: "ALL ZONES" },
      { task: "LETTER IN NAGAR NIGAM AUTHORITIES", assignedTo: "M. SAFDAR BHAI BETMA WALA / YUSUF BHAI", priority: "Critical", zone: "ALL ZONES" },
      { task: "LETTER TO AIRPORT AUTHORITIES", assignedTo: "Shk Khuzema Bhai Peti Wala", priority: "High", zone: "ALL ZONES" },
      { task: "LETTER TO RAILWAY AUTHORITIES", assignedTo: "M. Ammar Bhai Fahim", priority: "High", zone: "CMZ" },
      { task: "LETTER TO POLICE DEPARTMENT", assignedTo: "Murtaza Bhai Bhopal Wala", priority: "High", zone: "ALL ZONES" },
      { task: "LETTER TO TRAFFIC POLICE DEPARTMENT", assignedTo: "Adnan Bhai Bhanwrasa Wala / Burhanuddin Bhai", priority: "High", zone: "ALL ZONES" },
      { task: "ACTIVATE CENTRAIZED HELPLINE", assignedTo: "Abdeali Bhai Ziya", priority: "High", zone: "ALL ZONES" },
    ]),
  },
  {
    id: "procurement",
    name: "PROCUREMENT",
    chairman: "MOHAMMED BHAI NATALWALA",
    pc: "AHMED BHAI",
    rows: padRows([
      { task: "Confirm delivery and placement of all procured/rented assets like equipment, inventory, etc., across departments.", assignedTo: "Mustafa Tehsildar", priority: "Critical", zone: "ALL ZONES" },
      { task: "Start tagging all assets with proper inventory codes and initiate tracking through the asset management system.", assignedTo: "Mustafa Tehsildar", priority: "Critical", zone: "ALL ZONES" },
      { task: "Confirm all key vendors have delivered materials to site and verify their availability for replacements or shortages.", assignedTo: "Mohammed Natal", priority: "Critical", zone: "ALL ZONES" },
      { task: "Perform a final inventory count and match against procurement records to ensure all items are received.", assignedTo: "Ali Asger Theliwala", priority: "Critical", zone: "ALL ZONES" },
      { task: "Establish rapid procurement pathways for unexpected needs with pre-approved vendors.", assignedTo: "Ali Asger Theliwala", priority: "Critical", zone: "ALL ZONES" },
      { task: "Distribute and track material logs for each department to manage their usage efficiently.", assignedTo: "Adnan Najmi", priority: "High", zone: "ALL ZONES" },
    ]),
  },
  {
    id: "av",
    name: "AV",
    chairman: "MUSTAFA BHAI BADSHAH",
    pc: "AHMED BHAI",
    rows: padRows([
      { priority: "Critical", zone: "ALL ZONES" },
      { zone: "ALL ZONES" },
    ]),
  },
  {
    id: "it",
    name: "IT",
    chairman: "MUSTAFA MORWALA",
    pc: "AHMED BHAI",
    rows: padRows([
      { task: "PROVIDE WORKING INTERNET CONNECTION IN CENTRAL OFFICE", assignedTo: "Burhanuddin Kanchwala", priority: "Critical", zone: "CENTRAL OFFICE" },
      { task: "PROVIDE WORKING INTERNET CONNECTION IN CENTRAL OFFICE", assignedTo: "Burhanuddin Kanchwala", priority: "Critical", zone: "CMZ" },
      { assignedTo: "Burhanuddin Shakir", dependency: "PROCURMENT", priority: "High", zone: "ALL ZONES" },
    ]),
  },
  {
    id: "its",
    name: "ITS",
    chairman: "MUFADDAL RATA WALA",
    pc: "AHMED BHAI",
    rows: padRows([
      { task: "Laison with BGI Team for final flow map, so as to assign the various ITS Scanning points, between the queue for filtering the proxies.", assignedTo: "Murtaza shirani/ Saifuddin Shakir", dependency: "Final Flow Map", priority: "Critical", zone: "ALL ZONES" },
      { task: "Laison with Networking Team, to discuss about the internet connectivity over the ITS Scanning points and for the Back Office, CMZ and across All", assignedTo: "Mohammad Hamid", dependency: "Internet Connectivity", priority: "Critical", zone: "ALL ZONES" },
      { task: "To Call Meeting for all the HOD's and Designated persons for planning of the assigned tasks and TODO tasks assignments", assignedTo: "M.Mufaddal Rata", dependency: "Task Allocation", priority: "HIgh", zone: "ALL ZONES" },
      { task: "IVR Setup in Laison with ITS Team", assignedTo: "Murtaza Saifee", dependency: "IVR Setup", priority: "Medium" },
      { task: "Laison with hardware handling team, for the ITS scanning devices and its requirements over the zones.", assignedTo: "Shamoil Attar", dependency: "Hardware", priority: "HIgh" },
      { task: "Laison with Procurement team, for defining the need of various equipments, like, Laptops, Routers, Printers etc, for In Field Khidmat and", assignedTo: "Abdealli matka /Mufaddal Kannodwala", dependency: "Equipments/Devices", priority: "HIgh" },
      { task: "Laison with concerned person for setting up of Central Office & Toloba Office near zones.", assignedTo: "Hussain Dawaiwala", dependency: "TKM Office", priority: "HIgh" },
      { task: "Laison with MMR team for discussion over the On Arrival Scan requirement and Kiosk setups.", assignedTo: "Aliakbar Cyclewala", dependency: "Arrival Scanning", priority: "HIgh" },
      { task: "Training sessions for all zones and all scanning members", assignedTo: "Burhanuddin Saify", dependency: "Training", priority: "Medium" },
      { task: "Laison with Transportation Team for discussion of their requirement of Scanning points over the drop positions (if required).", assignedTo: "Taha Bagwala", dependency: "Requirement Gathering", priority: "Medium" },
    ]),
  },
  {
    id: "hr",
    name: "HR",
    chairman: "Sh YUSUF BHAI MALUBHAI",
    pc: "HATIM BHAI KANCHWALA",
    rows: padRows([
      { task: "DESK SETUP FOR HR REGISTRATION", assignedTo: "Khadija Ben Tajpurwala", priority: "Critical", zone: "ALL ZONES" },
      { task: "REQVISITION PROCESS FOR PAID HR", dependency: "Procurement", priority: "Critical", zone: "ALL ZONES" },
      { task: "DATA COLLECTION OF INTERNATIONAL HR COMING IN 0 HOUR", dependency: "CHAIRMAN'S", priority: "Critical", zone: "CENTRAL OFFICE" },
      { task: "Immediately replace absent or underperforming staff from standby pool.", assignedTo: "Mudreka Bhai Sabir", priority: "Critical" },
      { task: "PF + ESIC (WORKMENSHIP CONTRACT)", assignedTo: "Ammar Bhai Fahim", dependency: "FINANCE", priority: "Critical", zone: "CENTRAL OFFICE" },
      { task: "Confirm all departments have adequate manpower and backups.", assignedTo: "Mudreka Bhai Sabir" },
      { task: "Ensure all positions are occupied and operational.", assignedTo: "Sakina Ben Pardawala" },
      { task: "Ensure all KGs, volunteers and outsourced staff have valid ID cards.", assignedTo: "Ammar Bhai Badnawar" },
    ]),
  },
  {
    id: "cod",
    name: "COD",
    chairman: "MURTAZA BHAI CHADBHAI WALA",
    pc: "HATIM BHAI KANCHWALA",
    rows: padRows([
      { task: "OFFICE ALLOCATION", assignedTo: "Murtaza Bhai Chandbhaiwala", priority: "Critical", zone: "CENTRAL OFFICE" },
      { task: "MEETING ROOM SETUP", assignedTo: "Adam Boriwala", priority: "High", zone: "CENTRAL OFFICE" },
      { task: "MAWAID INFRA SETUP", priority: "High", zone: "CENTRAL OFFICE" },
      { task: "IT & WIFI SETUP", priority: "High", zone: "CENTRAL OFFICE" },
    ]),
  },
  {
    id: "accommodation",
    name: "ACCOMODATION",
    chairman: "M. IDREES BH BATTERYWALA",
    pc: "MUSTANSIR BH DAWAIWALA",
    rows: padRows([
      { task: "ACCOMODATE 14 QA SAHEBO IN THEIR ALLOCATED UTARA", assignedTo: "M. IDREES BH BATTERYWALA", priority: "Critical" },
      { task: "ACCOMODATE DARAJAH HADI ASHAR TALABAAT/TALEBAAT IN THEIR UTARA, IN CMZ VICINITY", assignedTo: "M. IDREES BH BATTERYWALA, ZAINAB BN FAHIM", priority: "Critical" },
      { task: "ACCOMODATE HIZB E SAIFEE, PRIORITY 1 KGs", assignedTo: "M. IDREES BH BATTERYWALA, ZAINAB BN FAHIM", priority: "Critical" },
      { task: "FINAL SURVEY WITH BS FOR REMAINING QA UTARA", assignedTo: "M. IDREES BH BATTERYWALA, ZAINAB BN FAHIM", priority: "High" },
      { task: "BOOK HOTELS FOR AQA MOULA MEHMAAN AND YEMENIS", assignedTo: "M ALIASGAR BH ZIA", priority: "Critical" },
    ]),
  },
  {
    id: "waaz-talaqqi",
    name: "WAAZ TALAQQI",
    chairman: "SHABBIR BHAI ABDABHAIWALA",
    pc: "HATIM BHAI KANCHWALA",
    rows: padRows([
      { task: "Liason with construction department for Office Setup for MHB Talabulilm, Mukhaiyyamul Quran and Istibsar", dependency: "Construction", priority: "Critical", zone: "CMZ" },
      { task: "Laison with IPMO and setup Office for IPMO", dependency: "COD" },
    ]),
  },
];

const ADMIN_DEFAULT = { username: "admin", password: "ashara1448" };
const STORAGE_KEY = "fasal-planning-v1";
const AUTH_KEY = "fasal-planning-auth";
